name: Kubernetes Deployment

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: 
      - self-hosted
      - label-1  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2




      - name: Set up Minikube
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https

          # Install Minikube
          curl -Lo minikube https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

          # Start Minikube
          minikube start --driver=docker

      - name: Start Minikube
        run: |
          minikube start --driver=docker


      - name: Kubernetes Login
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}  # This should be the base64-encoded kubeconfig file
        run: |
          echo "$KUBECONFIG" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Verify kubectl configuration
        run: |
          kubectl config view

      - name: Debug kubeconfig
        run: |
          echo "$KUBECONFIG" | base64 --decode > kubeconfig
          cat kubeconfig  # Output the kubeconfig contents for debugging purposes

      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}  # Ensure this secret is set in your repository settings
        run: |
          kubectl apply -f testpod.yml  
