name: Kubernetes Deployment

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl with GitHub Secret
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 777 $HOME/.kube/config

      - name: Verify kubectl configuration
        run: |
          kubectl config view
  
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f testpod.yml
          # Add any other kubectl commands as needed
