name: Kubernetes Deployment

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Set up Minikube
        run: |
          curl -Lo minikube https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/      


      - name: Kubernetes Login
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}  # This should be the base64-encoded kubeconfig file
        run: |
          echo "$KUBECONFIG" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Verify kubectl configuration
        run: |
          kubectl config view

      - name: Debug kubeconfig
        run: |
          echo "$KUBECONFIG" | base64 --decode > kubeconfig
          cat kubeconfig  # Output the kubeconfig contents for debugging purposes

      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}  # Ensure this secret is set in your repository settings
        run: |
          kubectl apply -f testpod.yml  
